---
- hosts: all
  vars:
    tdaggr_primary: "1.2.3.4"
    tdaggr_secondary: "5.6.7.8"
    tailfiles:
      /var/log/bootstrap.log:
        tag: bootstrap
        format: apache2
      /var/log/dmesg:
        tag: dmesg

  roles:
    - tdagentclient
