---
- hosts: logshipper
  sudo: yes
  vars:
    td_agent_aggr: false  # True => aggregator mode, False => Log shipping mode
    tdaggr_primary: "aggr.vm"
    tdaggr_secondary: "5.6.7.8"
    tailfiles:
      /var/log/bootstrap.log:
        tag: bootstrap
        format: apache2  # Optional, defaults to none
      /var/log/dmesg:
        tag: dmesg

  roles:
    - ansible-fluentd
    - tdagentclient

- hosts: aggr
  sudo: yes
  vars:
    td_agent_aggr: true  # True => aggregator mode, False => Log shipping mode
    s3_path: /foo
    aws_key_id: AK
    aws_sec_key: AK
    s3_bucket: poundbay_whateva_that_is
    s3_endpoint: s3.amazonaws.com

  roles:
    - ansible-fluentd
    - tdagentclient

